name: Tests and Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.flake8'
      - 'requirements.txt'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.flake8'
      - 'requirements.txt'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Run tests via test.sh
        run: |
          bash test.sh -v
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          # Removing test_output/ and .coverage as they are no longer used
          # path: |
          #   test_output/
          #   .coverage
          if-no-files-found: ignore 